version: '3.8'

services:
  frontend:
    image: crpi-mybfxaei46yf37zf.cn-hangzhou.personal.cr.aliyuncs.com/ubuntu20_dock/conlaboro-frontend:latest
    ports:
      - "80:80"
    networks:
      - conlaboro-network
    depends_on:
      - backend

  backend:
    image: crpi-mybfxaei46yf37zf.cn-hangzhou.personal.cr.aliyuncs.com/ubuntu20_dock/conlaboro-backend:latest
    ports:
      - "8080:8080"
    networks:
      - conlaboro-network
    depends_on:
      - postgres
    env_file:
      - backend/.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/conlaboro
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - conlaboro-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=conlaboro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  conlaboro-network:
    driver: bridge

volumes:
  postgres-data:
